/*------------------------------------------------------------
Tests the AudioManager

Uses the boost test library.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


Written by Maxwell Miller
-------------------------------------------------------------*/

/*

	Tests to add: 

	AddClip
	AddSource
	RemoveClip
	RemoveSource
	AddClipToSource
	SetListener
	GetListener -> Change stuff
	GetClip -> Change stuff
	GetSource -> Change stuff 

	AudioManager::LoadClip(U32 id, string filepath) => Should be created



#include <boost/test/unit_test.hpp>
#include <UnitTests/TestHelper.h>
#include <Engine/Atom.h>
#include <Engine/AudioManager.h>
#include <Engine/AudioListener.h>
#include <Engine/AudioClip.h>
#include <Engine/AudioSource.h>

namespace KE = KillerEngine;

BOOST_AUTO_TEST_CASE(AudioManagerAddAndRemove)
{
	shared_ptr<KE::AudioListener> listener = make_shared<KE::AudioListener>();

	KE::AudioManager::Instance()->SetListener(listener);

	shared_ptr<KE::AudioClip> clip = make_shared<KE::AudioClip>();
	clip->LoadWAV("../Assets/Audio/Komiku_04_Skate.wav");

	KE::AudioManager::Instance()->AddClip(1, clip);

	shared_ptr<KE::AudioClip> clip2 = make_shared<KE::AudioClip>();
	clip2->LoadWAV("../Assets/Audio/Komiku_07_Battle_of_Pogs.wav");

	shared_ptr<KE::AudioSource> source = make_shared<KE::AudioSource>();
	source->AddClip(clip2);

	KE::AudioManager::Instance()->AddSource(1, source);
	KE::AudioManager::Instance()->AddClip(2, clip2);

	shared_ptr<KE::AudioSource> source2 = make_shared<KE::AudioSource>();

	KE::AudioManager::Instance()->AddSource(2, source2);

	KE::AudioManager::Instance()->AddClipToSource(2, 2);

	//Check that sources and clips have been added correctly. 
	//Assuming that not nullptr is enough to know its ok. 
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetListener(), nullptr);
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetClip(1), nullptr);
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetSource(1), nullptr);
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetSource(2)->GetClip(), nullptr);

	//Check that we can remove clips and sources
	KE::AudioManager::Instance()->RemoveClip(1);
	KE::AudioManager::Instance()->RemoveSource(1);

	BOOST_CHECK_EQUAL(KE::AudioManager::Instance()->GetClip(1), nullptr);
	BOOST_CHECK_EQUAL(KE::AudioManager::Instance()->GetSource(1), nullptr);

	//Check that load clip is working
	KE::AudioManager::Instance()->LoadClip(3, "../Assets/Audio/Komiku_04_Skate.wav");
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetClip(3), nullptr);

	shared_ptr<KE::AudioSource> source3 = make_shared<KE::AudioSource>();
	KE::AudioManager::Instance()->AddSource(3, source);

	KE::AudioManager::Instance()->AddClipToSource(3, 3);

	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetSource(3), nullptr);
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetSource(3)->GetClip(), nullptr);

	//Check for SetListener(void)
	//First, unset the listener. Then call SetListener(void)
	KE::AudioManager::Instance()->SetListener(nullptr);
	BOOST_CHECK_EQUAL(KE::AudioManager::Instance()->GetListener(), nullptr);

	KE::AudioManager::Instance()->SetListener();
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetListener(), nullptr);

	//Test Load Source
	KE::AudioManager::Instance()->LoadSource(4);
	BOOST_CHECK_NE(KE::AudioManager::Instance()->GetSource(4), nullptr);
}

*/