/*========================================================================
Unit Tests written for the GameObject3D class. This should ensure that 
the class is always working as it should be. 

Because the GameObject3D is an abstract class, a defined class will be
provided in this file. This will be the first portion of the file. The
tests will take place after the class declaration.

Uses the boost test library.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


Written by Maxwell Miller
========================================================================*/
#include <boost/test/unit_test.hpp>
#include <Engine/Atom.h>
#include <Engine/GameObject3D.h>
#include <Engine/Vector3.h>

namespace KE = KillerEngine;
namespace KM = KillerMath; 

class DefinedObject3D : public KE::GameObject3D
{
public:
	DefinedObject3D(void) 
	{  }

	~DefinedObject3D(void)
	{  }

	void v_Update(void)
	{  }
};

BOOST_AUTO_TEST_CASE(GameObject3D_Constructors_And_ID_Accessors)
{
	DefinedObject3D d1 {  };
	DefinedObject3D d2 {  };

	DefinedObject3D copyObject {d1};

	BOOST_CHECK_EQUAL(d1.GetID(), 1);
	BOOST_CHECK_EQUAL(d2.GetID(), 2);
	BOOST_CHECK_EQUAL(copyObject.GetID(), 1);

	BOOST_CHECK_EQUAL(d1.GetActive(), true);
}

BOOST_AUTO_TEST_CASE(GameObject3D_Active_State_Accessors)
{
	DefinedObject3D d {  };

	BOOST_CHECK_EQUAL(d.GetActive(), true);

	d.SetInactive();

	BOOST_CHECK_EQUAL(d.GetActive(), false);

	d.SetActive();

	BOOST_CHECK_EQUAL(d.GetActive(), true);
}

BOOST_AUTO_TEST_CASE(GameObject3D_Position_Accessors)
{
	DefinedObject3D d {  };

	d.SetPosition(KM::Vector3(5.0f, 10.0f, 30.0f));

	BOOST_CHECK_EQUAL(d.GetPosition().GetX(), 5.0f);
	BOOST_CHECK_EQUAL(d.GetPosition().GetY(), 10.0f);
	BOOST_CHECK_EQUAL(d.GetPosition().GetZ(), 30.0f);

	d.SetPosition(2.0f, 3.0f, 6.0f);

	BOOST_CHECK_EQUAL(d.GetPosition().GetX(), 2.0f);
	BOOST_CHECK_EQUAL(d.GetPosition().GetY(), 3.0f);
	BOOST_CHECK_EQUAL(d.GetPosition().GetZ(), 6.0f);
}

BOOST_AUTO_TEST_CASE(GameObject3D_Dimension_Accessors)
{
	DefinedObject3D d {  };

	d.SetWidth(12.0f);
	d.SetHeight(3.0f);
	d.SetDepth(5.0f);

	BOOST_CHECK_EQUAL(d.GetWidth(), 12.0f);
	BOOST_CHECK_EQUAL(d.GetHeight(), 3.0f);
	BOOST_CHECK_EQUAL(d.GetDepth(), 5.0f);

	d.SetDimensions(4.0f, 15.0f, 2.0f);

	BOOST_CHECK_EQUAL(d.GetWidth(), 4.0f);
	BOOST_CHECK_EQUAL(d.GetHeight(), 15.0f);
	BOOST_CHECK_EQUAL(d.GetDepth(), 2.0f);
}