/*------------------------------------------------------------
This file will test the functionality of the Level class which
will be used in the Killer Engine.

Uses the boost test library.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


Written by Maxwell Miller
-------------------------------------------------------------*/

#include "stdafx.h"
#include <boost/test/unit_test.hpp>
#include <UnitTests/TestHelper.h>
#include <Engine/Atom.h>
#include <Engine/Level.h>
#include <Engine/GameObject2D.h>
#include <Engine/RigidBody2D.h>

namespace TE = Tempest;
namespace TP =TempestPhysics;

/*

Disabled until gameobject can be smarter

//==========================================================================================================================
//Concrete Level
//==========================================================================================================================
class TestLevel : public TE::Level
{
public:
    TestLevel(void)
    {
        Level::SetCameraOrthographic(-1.0f, 1.0f, -1.0f, 1.0f, -1.0f, 1.0f);
    }

    ~TestLevel(void)
    {  }

    void v_Init(void) final
    {  }

    void v_Update(void) final
    {  }
};

class TestLevelDefinedGameObject : public TE::GameObject
{
public:
    TestLevelDefinedGameObject(void)
    {
        GameObject::MakeSprite();
    };

    ~TestLevelDefinedGameObject(void)
    {  };

    void v_Update(void)
    {  };
};

//==========================================================================================================================
//Tests
//==========================================================================================================================

BOOST_AUTO_TEST_CASE(LevelSetAndGetDepthTests)
{
    TestLevel test { };
    test.SetDepth(200);
    test.SetNearBorder(-100);
    test.SetFarBorder(100);

    BOOST_CHECK_EQUAL(test.GetDepth(), 200);
    BOOST_CHECK_EQUAL(test.GetNearBorder(), -100);
    BOOST_CHECK_EQUAL(test.GetFarBorder(), 100);
}

BOOST_AUTO_TEST_CASE(LevelAddAndRemoveObjects)
{
    TestLevel* test = new TestLevel();
    test->SetDepth(200);
    test->SetNearBorder(-100);
    test->SetFarBorder(100);

    shared_ptr<TestLevelDefinedGameObject> obj1 { new TestLevelDefinedGameObject() };

    U32 obj1ID = obj1->GetID();

    test->AddObjectToLevel(obj1);

    auto copy1 = test->GetGameObject(obj1ID);

    BOOST_CHECK_EQUAL(obj1ID, copy1->GetID());

    test->RemoveObjectFromLevel(obj1ID);

    auto copy2 = test->GetGameObject(obj1ID);

    BOOST_CHECK_EQUAL(copy2, nullptr);

/*
    Error in GetShader call is blocking this code from running. It should be fixec, but I have
    already spent too much time trying to get this to work. Calling it for now, since this is an
    issue in the unit test framework, not the code itself.

    shared_ptr<TP::RigidBody2D> RigidBody2D { new TP::RigidBody2D() };

    U32 RigidBody2DID = RigidBody2D->GetID();

    test->AddObjectToLevel(RigidBody2D);

    auto RigidBody2DCopy = test->GetRigidBody2D(RigidBody2DID);

    BOOST_CHECK_EQUAL(RigidBody2DCopy->GetID(), RigidBody2DID);

    test->RemoveObjectFromLevel(RigidBody2DID);

    auto RigidBody2DCopy2 = test->GetRigidBody2D(RigidBody2DID);

    BOOST_CHECK_EQUAL(RigidBody2DCopy2, nullptr);

}

*/