/*------------------------------------------------------------
This file will test the functionality of the Vector3 class which
will be used in the Killer1 Engine. Most of the examples and all
of the equations are from 3D Math Primer for Graphics and Game
Development by Dunn and Parberry (awesome book for those who 
wish to learn). 

Uses the boost test library.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


Written by Maxwell Miller
-------------------------------------------------------------*/

#include <boost/test/unit_test.hpp>
#include <UnitTests/TestHelper.h>
#include <Engine/Atom.h>
#include <Engine/Matrix3.h>
#include <Engine/Vector3.h>


namespace KM = KillerMath;

BOOST_AUTO_TEST_CASE(Matrix3DefaultConstructor) 
{
	KM::Matrix3 M1{};

	BOOST_CHECK_EQUAL(M1[0][x], 1.0f);
	BOOST_CHECK_EQUAL(M1[0][y], 0.0f);
	BOOST_CHECK_EQUAL(M1[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(M1[1][x], 0.0f);
	BOOST_CHECK_EQUAL(M1[1][y], 1.0f);
	BOOST_CHECK_EQUAL(M1[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(M1[2][x], 0.0f);
	BOOST_CHECK_EQUAL(M1[2][y], 0.0f);
	BOOST_CHECK_EQUAL(M1[2][z], 1.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3DiagnalConstructor) 
{
	KM::Matrix3 M1(5.0f);

	BOOST_CHECK_EQUAL(M1[0][x], 5.0f);
	BOOST_CHECK_EQUAL(M1[0][y], 0.0f);
	BOOST_CHECK_EQUAL(M1[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(M1[1][x], 0.0f);
	BOOST_CHECK_EQUAL(M1[1][y], 5.0f);
	BOOST_CHECK_EQUAL(M1[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(M1[2][x], 0.0f);
	BOOST_CHECK_EQUAL(M1[2][y], 0.0f);
	BOOST_CHECK_EQUAL(M1[2][z], 5.0f);
}


BOOST_AUTO_TEST_CASE(Matrix3Vector3Constructor) 
{
	KM::Vector3 vecX {1.0f, 2.0f, 3.0f};
	KM::Vector3 vecY {15.0f, 25.0f, 35.0f};
	KM::Vector3 vecZ {30.0f, 50.0f, 70.0f};

	KM::Matrix3 mat(vecX, vecY, vecZ);

	BOOST_CHECK_EQUAL(mat[0][x], 1.0f);
	BOOST_CHECK_EQUAL(mat[0][y], 2.0f);
	BOOST_CHECK_EQUAL(mat[0][z], 3.0f);
	
	BOOST_CHECK_EQUAL(mat[1][x], 15.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 25.0f);
	BOOST_CHECK_EQUAL(mat[1][z], 35.0f);
	
	BOOST_CHECK_EQUAL(mat[2][x], 30.0f);
	BOOST_CHECK_EQUAL(mat[2][y], 50.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 70.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3CopyConstructor)
{
	KM::Matrix3 A(10.0f);

	KM::Matrix3 B = A;

	BOOST_CHECK_EQUAL(B[0][x], 10.0f);
	BOOST_CHECK_EQUAL(B[0][y], 0.0f);
	BOOST_CHECK_EQUAL(B[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(B[1][x], 0.0f);
	BOOST_CHECK_EQUAL(B[1][y], 10.0f);
	BOOST_CHECK_EQUAL(B[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(B[2][x], 0.0f);
	BOOST_CHECK_EQUAL(B[2][y], 0.0f);
	BOOST_CHECK_EQUAL(B[2][z], 10.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3OperatorMultiply) {
	KM::Matrix3 A
	(
		KM::Vector3(3.0f, 5.0f, 7.0f),
		KM::Vector3(6.0f, 3.0f, 8.0f),
		KM::Vector3(9.0f, 3.0f, 5.0f)
	);

	KM::Matrix3 B
	(
		KM::Vector3(2.0f, 5.0f, 1.0f),
		KM::Vector3(6.0f, 2.0f, 2.0f),
		KM::Vector3(2.0f, 3.0f, 2.0f)
	);

	KM::Matrix3 C = A * B;

	BOOST_CHECK_EQUAL(C[0][x], 45.0f);
	BOOST_CHECK_EQUAL(C[0][y], 28.0f);
	BOOST_CHECK_EQUAL(C[0][z], 59.0f);
	
	BOOST_CHECK_EQUAL(C[1][x], 48.0f);
	BOOST_CHECK_EQUAL(C[1][y], 42.0f);
	BOOST_CHECK_EQUAL(C[1][z], 68.0f);
	
	BOOST_CHECK_EQUAL(C[2][x], 42.0f);
	BOOST_CHECK_EQUAL(C[2][y], 25.0f);
	BOOST_CHECK_EQUAL(C[2][z], 48.0f);
}


BOOST_AUTO_TEST_CASE(Matrix3OperatorEQMultiply) {
	KM::Matrix3 A
	(
		KM::Vector3(3.0f, 5.0f, 7.0f),
		KM::Vector3(6.0f, 3.0f, 8.0f),
		KM::Vector3(9.0f, 3.0f, 5.0f)
	);

	KM::Matrix3 B
	(
		KM::Vector3(2.0f, 5.0f, 1.0f),
		KM::Vector3(6.0f, 2.0f, 2.0f),
		KM::Vector3(2.0f, 3.0f, 2.0f)
	);

	A = A * B;

	BOOST_CHECK_EQUAL(A[0][x], 45.0f);
	BOOST_CHECK_EQUAL(A[0][y], 28.0f);
	BOOST_CHECK_EQUAL(A[0][z], 59.0f);
	
	BOOST_CHECK_EQUAL(A[1][x], 48.0f);
	BOOST_CHECK_EQUAL(A[1][y], 42.0f);
	BOOST_CHECK_EQUAL(A[1][z], 68.0f);
	
	BOOST_CHECK_EQUAL(A[2][x], 42.0f);
	BOOST_CHECK_EQUAL(A[2][y], 25.0f);
	BOOST_CHECK_EQUAL(A[2][z], 48.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3Reset)
{
	KM::Matrix3 mat
	(
		KM::Vector3(2.0f, 4.0f, 10.0f),
		KM::Vector3(10.0f, 15.0f, 25.0f),
		KM::Vector3(1.0f, 2.0f, 3.0f)
	);

	mat.Reset();

	BOOST_CHECK_EQUAL(mat[0][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[0][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat[1][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat[2][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[2][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 0.0f);

	mat.Reset(1.0f);

	BOOST_CHECK_EQUAL(mat[0][x], 1.0f);
	BOOST_CHECK_EQUAL(mat[0][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat[1][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 1.0f);
	BOOST_CHECK_EQUAL(mat[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat[2][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[2][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 1.0f);
}


BOOST_AUTO_TEST_CASE(Matrix3Scale)
{
	KM::Matrix3 mat(1.0f);

	mat.SetScale(3.0f, 4.0f);

	BOOST_CHECK_EQUAL(mat[0][x], 3.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 4.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 1.0f);

	mat.SetScale(2.0f, 2.0f, 2.0f);

	BOOST_CHECK_EQUAL(mat[0][x], 2.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 2.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 2.0f);

	mat.SetScale(KM::Vector3(5.0f, 4.0f, 3.0f));

	BOOST_CHECK_EQUAL(mat[0][x], 5.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 4.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 3.0f);
	
	KM::Vector3 vec{2.0f, 3.0f, 10.0f};
	vec.Make2D();

	mat.SetScale(vec);

	BOOST_CHECK_EQUAL(mat[0][x], 2.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 3.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 1.0f);

	vec.Set(10.0f, 20.0f, 5.0f);
	vec.Make3D();

	mat.SetScale(vec);

	BOOST_CHECK_EQUAL(mat[0][x], 10.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 20.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 5.0f);

	KM::Matrix3 mat2 = KM::Matrix3::Scale(2.0f, 5.0f);

	BOOST_CHECK_EQUAL(mat2[0][x], 2.0f);
	BOOST_CHECK_EQUAL(mat2[1][y], 5.0f);
	BOOST_CHECK_EQUAL(mat2[2][z], 1.0f);

	KM::Matrix3 mat3 = KM::Matrix3::Scale(6.0f, 4.0f, 8.0f);

	BOOST_CHECK_EQUAL(mat3[0][x], 6.0f);
	BOOST_CHECK_EQUAL(mat3[1][y], 4.0f);
	BOOST_CHECK_EQUAL(mat3[2][z], 8.0f);

	KM::Matrix3 mat4 = KM::Matrix3::Scale(KM::Vector3(13.0f, 50.0f, 2.0f));

	BOOST_CHECK_EQUAL(mat4[0][x], 13.0f);
	BOOST_CHECK_EQUAL(mat4[1][y], 50.0f);
	BOOST_CHECK_EQUAL(mat4[2][z], 2.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3AddScale)
{
	KM::Matrix3 mat(1.0f);

	mat.AddScale(3.0f, 2.0f);

	BOOST_CHECK_EQUAL(mat[0][x], 4.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 3.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 1.0f);

	mat.AddScale(2.0f, 2.0f, 2.0f);

	BOOST_CHECK_EQUAL(mat[0][x], 6.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 5.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 3.0f);

	KM::Vector3 vec{3.0f, 4.0f, 5.0f};
	vec.Make2D();

	mat.AddScale(vec);

	BOOST_CHECK_EQUAL(mat[0][x], 9.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 9.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 3.0f);

	vec.Make3D();
	mat.AddScale(vec);

	BOOST_CHECK_EQUAL(mat[0][x], 12.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 13.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 8.0f);
}


BOOST_AUTO_TEST_CASE(Matrix3Rotation)
{
	KM::Matrix3 mat{1.0f};

	mat.SetRotateX(-22.0f);

	BOOST_CHECK_EQUAL(mat[0][x], 1.0f);
	BOOST_CHECK_EQUAL(mat[0][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[0][z], 0.0f);

	BOOST_CHECK_EQUAL(mat[1][x], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][y]), 0.92718f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][z]), 0.37461f);
	
	BOOST_CHECK_EQUAL(mat[2][x], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][y]), -0.37461f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][z]), 0.92718f);

	KM::Matrix3 xMat = KM::Matrix3::RotateX(-22.0f);

	BOOST_CHECK_EQUAL(xMat[0][x], 1.0f);
	BOOST_CHECK_EQUAL(xMat[0][y], 0.0f);
	BOOST_CHECK_EQUAL(xMat[0][z], 0.0f);

	BOOST_CHECK_EQUAL(xMat[1][x], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(xMat[1][y]), 0.92718f);
	BOOST_CHECK_EQUAL(RoundFloat(xMat[1][z]), 0.37461f);
	
	BOOST_CHECK_EQUAL(xMat[2][x], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(xMat[2][y]), -0.37461f);
	BOOST_CHECK_EQUAL(RoundFloat(xMat[2][z]), 0.92718f);


	mat.SetRotateY(30.0f);

	BOOST_CHECK_EQUAL(RoundFloat(mat[0][x]), 0.86603f);
	BOOST_CHECK_EQUAL(mat[0][y], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[0][z]),0.50000f);
	
	BOOST_CHECK_EQUAL(mat[1][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 1.0f);
	BOOST_CHECK_EQUAL(mat[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][x]), -0.50000f);
	BOOST_CHECK_EQUAL(mat[2][y], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][z]), 0.86603f);

	KM::Matrix3 yMat = KM::Matrix3::RotateY(30.0f);

	BOOST_CHECK_EQUAL(RoundFloat(yMat[0][x]), 0.86603f);
	BOOST_CHECK_EQUAL(yMat[0][y], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(yMat[0][z]),0.50000f);
	
	BOOST_CHECK_EQUAL(yMat[1][x], 0.0f);
	BOOST_CHECK_EQUAL(yMat[1][y], 1.0f);
	BOOST_CHECK_EQUAL(yMat[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(RoundFloat(yMat[2][x]), -0.50000f);
	BOOST_CHECK_EQUAL(yMat[2][y], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(yMat[2][z]), 0.86603f);

	mat.SetRotateZ(26.0f);

	BOOST_CHECK_EQUAL(RoundFloat(mat[0][x]), 0.89879f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[0][y]), -0.43837f);
	BOOST_CHECK_EQUAL(mat[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][x]), 0.43837f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][y]), 0.89879f);
	BOOST_CHECK_EQUAL(mat[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat[2][x], 0.0f);
	BOOST_CHECK_EQUAL(mat[2][y], 0.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 1.0f);

	KM::Matrix3 zMat = KM::Matrix3::RotateZ(26.0f);

	BOOST_CHECK_EQUAL(RoundFloat(zMat[0][x]), 0.89879f);
	BOOST_CHECK_EQUAL(RoundFloat(zMat[0][y]), -0.43837f);
	BOOST_CHECK_EQUAL(zMat[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(RoundFloat(zMat[1][x]), 0.43837f);
	BOOST_CHECK_EQUAL(RoundFloat(zMat[1][y]), 0.89879f);
	BOOST_CHECK_EQUAL(zMat[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(zMat[2][x], 0.0f);
	BOOST_CHECK_EQUAL(zMat[2][y], 0.0f);
	BOOST_CHECK_EQUAL(zMat[2][z], 1.0f);
/*	
	mat.Rotate(30.0f, 78.0f, 245.0f);

	BOOST_CHECK_EQUAL(RoundFloat(mat[0][x]), -0.08787f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[0][y]), 0.18843);
	BOOST_CHECK_EQUAL(RoundFloat(mat[0][z]), 0.97815f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][x]), -0.99158f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][y]), 0.07725f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[1][z]), -0.10396f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][x]), -0.09515f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][y]), -0.97904f);
	BOOST_CHECK_EQUAL(RoundFloat(mat[2][z]), 0.18006f);
*/
}


BOOST_AUTO_TEST_CASE(Matrix3Transpose)
{
	KM::Matrix3 mat
	{
		1.0f, 1.0f, 1.0f,
		2.0f, 2.0f, 2.0f,
		3.0f, 3.0f, 3.0f,
	};

	mat.Transpose();

	BOOST_CHECK_EQUAL(mat[0][x], 1.0f);
	BOOST_CHECK_EQUAL(mat[0][y], 2.0f);
	BOOST_CHECK_EQUAL(mat[0][z], 3.0f);
	
	BOOST_CHECK_EQUAL(mat[1][x], 1.0f);
	BOOST_CHECK_EQUAL(mat[1][y], 2.0f);
	BOOST_CHECK_EQUAL(mat[1][z], 3.0f);
	
	BOOST_CHECK_EQUAL(mat[2][x], 1.0f);
	BOOST_CHECK_EQUAL(mat[2][y], 2.0f);
	BOOST_CHECK_EQUAL(mat[2][z], 3.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3ComponentMultiplication)
{
	KM::Matrix3 mat1
	{
		1.0f, 1.0f, 1.0f,
		2.0f, 2.0f, 2.0f,
		3.0f, 3.0f, 3.0f,
	};

	KM::Matrix3 mat2{5.0f};

	mat1.ComponentMulti(mat2);

	BOOST_CHECK_EQUAL(mat1[0][x], 5.0f);
	BOOST_CHECK_EQUAL(mat1[0][y], 0.0f);
	BOOST_CHECK_EQUAL(mat1[0][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat1[1][x], 0.0f);
	BOOST_CHECK_EQUAL(mat1[1][y], 10.0f);
	BOOST_CHECK_EQUAL(mat1[1][z], 0.0f);
	
	BOOST_CHECK_EQUAL(mat1[2][x], 0.0f);
	BOOST_CHECK_EQUAL(mat1[2][y], 0.0f);
	BOOST_CHECK_EQUAL(mat1[2][z], 15.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3Determinate)
{
	KM::Matrix3 mat
	{
		12.0f, 6.0f, 65.0f,
		3.0f, 52.0f, 8.0f,
		5.0f, 4.0f, 2.0f,
	};

	BOOST_CHECK_EQUAL(mat.Determinate(), -15052.0f);

	KM::Matrix3 mat2
	{
		1.0f, 6.0f, 6.0f,
		3.0f, 5.0f, 8.0f,
		5.0f, 4.0f, 2.0f,
	};

	BOOST_CHECK_EQUAL(mat2.Determinate(), 104.0f);
}

BOOST_AUTO_TEST_CASE(Matrix3Inverse)
{
	KM::Matrix3 mat1 
	{ 
		3.0f, 18.0f, 1.0f,
		8.0f, 0.0f, 9.0f,
		1.0f, 2.0f, 0.0f
	};

	mat1.SetInverse();

	BOOST_CHECK_EQUAL(RoundFloat(mat1[0][x]), -0.14516f);
	BOOST_CHECK_EQUAL(RoundFloat(mat1[0][y]), 0.01613f);
	BOOST_CHECK_EQUAL(RoundFloat(mat1[0][z]), 1.30645f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat1[1][x]), 0.07258f);
	BOOST_CHECK_EQUAL(RoundFloat(mat1[1][y]), -0.00806f);
	BOOST_CHECK_EQUAL(RoundFloat(mat1[1][z]), -0.15323f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat1[2][x]), 0.12903f);
	BOOST_CHECK_EQUAL(RoundFloat(mat1[2][y]), 0.09677f);
	BOOST_CHECK_EQUAL(RoundFloat(mat1[2][z]), -1.16129f);

	//KM::Matrix3 mat2 = mat1.GetInverse();

/*
	This should work, but for some reason [1][y] is wrong, and I do not know why
	It is coming up ad like, -5.something something. Not sure why. Could cause
	problems later for sure though...

	BOOST_CHECK_EQUAL(RoundFloat(mat2[0][x]), 3.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[0][y]), 18.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[0][z]), 1.0f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat2[1][x]), 8.0f);
	BOOST_CHECK_EQUAL(mat2[1][y], 0.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[1][z]), 9.0f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat2[2][x]), 1.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[2][y]), 2.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[2][z]), 0.0f);

	BOOST_CHECK_EQUAL(RoundFloat(mat2[3][x]), 7.0f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[3][y]), 2.99999f);
	BOOST_CHECK_EQUAL(RoundFloat(mat2[3][z]), 9.0f);
*/

	KM::Matrix3 mat3
	{
		8.0f, 6.0f, 7.0f,
		6.0f, 7.0f, 8.0f,
		7.0f, 8.0f, 6.0f
	};

	KM::Matrix3 mat4 = mat3.GetInverse();

	BOOST_CHECK_EQUAL(RoundFloat(mat4[0][x]), 0.34921f);
	BOOST_CHECK_EQUAL(RoundFloat(mat4[0][y]), -0.31746f);
	BOOST_CHECK_EQUAL(RoundFloat(mat4[0][z]), 0.01587f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat4[1][x]), -0.31746f);
	BOOST_CHECK_EQUAL(RoundFloat(mat4[1][y]), 0.01587f);
	BOOST_CHECK_EQUAL(RoundFloat(mat4[1][z]), 0.34921f);
	
	BOOST_CHECK_EQUAL(RoundFloat(mat4[2][x]), 0.01587f);
	BOOST_CHECK_EQUAL(RoundFloat(mat4[2][y]), 0.34921f);
	BOOST_CHECK_EQUAL(RoundFloat(mat4[2][z]), -0.317460001f);
}