/*------------------------------------------------------------
This file will test the functionality of the Vector class which
will be used in the Killer1 Engine. Most of the examples and all
of the equations are from 3D Math Primer for Graphics and Game
Development by Dunn and Parberry (awesome book for those who
wish to learn).

Uses the boost test library.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


Written by Maxwell Miller
-------------------------------------------------------------*/

#include <boost/test/unit_test.hpp>
#include <Engine/Atom.h>
#include <Engine/ParticleForceRegistry.h>
#include <Engine/ParticleGravityForce.h>
#include <Engine/Particle2D.h>
#include <Engine/Vector2.h>

namespace KM = KillerMath;
namespace KP = KillerPhysics;

/*
BOOST_AUTO_TEST_CASE(Particle2D_ForceRegistration)
{
	shared_ptr<KP::Particle2D> p { new KP::Particle2D() };
	shared_ptr<KP::Particle2DGravityForce> gravity { new KP::Particle2DGravityForce(KM::Vector2(0.0f -100.0f)) };
	KP::Particle2DForceRegistry registry { };

	registry.Add(p, gravity);

	p->SetPosition(KM::Vector2(0.0f, 0.0f));
	p->SetMass(100.0f);

	registry.UpdateForces();
	p->Integrate();
	registry.UpdateForces();
	p->Integrate();
	
	BOOST_CHECK_LT(p->GetPosition().GetY(), 0.0f);
}
*/